 language: node_js
 node_js:
   - "0.10"
 services:
   - mongodb
 before_script:
   - npm install -g grunt-cli
   - npm install
   - node app.js
 notifications:
   email:
     - frontend-team@wandoujia.com
     - wangye.zhao@wandoujia.com
     - miaojian@wandoujia.com
